#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))

@test(0, "running vmm")
def test_vmm():
    r.run_qemu(shell_script([
        'vmm'
    ]), timeout=600)

@test(100, "vmm: start in guest", parent=test_vmm)
def test_vmm_guest_start():
    r.match("^Start in guest kernel$")

run_tests()
